[package]
name = "ch1-1_hello2"
version = "0.1.0"
authors = ["anifilm <anifilm02@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
